services:
  openapi-generator:
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    command: sleep infinity
    extra_hosts:
        - "host.docker.internal:host-gateway"
    environment:
      PHP_EXTENSION_XDEBUG: 1
      PHP_INI_XDEBUG__CLIENT_HOST: host.docker.internal
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - type: bind
        source: ./
        target: /var/www/html

